name: XeonSuiteBan
version: ${project.version}
description: Banplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.ban.Banplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]
commands:
  ban:
    description: Ban a player
  tempban:
    description: Tempban a player
  kick:
    description: Kick a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  tempmute:
    description: Tempmute a player
  unmute:
    description: Unmute a player
permissions:
    xeonSuite.ban.team:
        description: Alle Permissions
        children:
            xeonSuite.ban.ban: true
            xeonSuite.ban.tempban: true
            xeonSuite.ban.unban: true
            xeonSuite.ban.kick: true
            xeonSuite.ban.mute: true
            xeonSuite.ban.tempmute: true
            xeonSuite.ban.unmute: true
            xeonSuite.ban.notifyinfo: true
        default: op
    xeonSuite.ban.ban:
        description: Ban a player permanently
        default: op
    xeonSuite.ban.tempban:
        description: Tempban a player
        default: op
    xeonSuite.ban.unban:
        description: Unban a player
        default: op
    xeonSuite.ban.kick:
        description: Kick a player
        default: op
    xeonSuite.ban.mute:
        description: Mute a player permanently
        default: op
    xeonSuite.ban.tempmute:
        description: Tempmute a player
        default: op
    xeonSuite.ban.unmute:
        description: Unmute a player
        default: op