name: XeonSuiteBan
version: ${project.version}.b${build.number}
description: Banplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.ban.Banplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]
commands:
  ban:
    description: Ban a player
  tempban:
    description: Tempban a player
  kick:
    description: Kick a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  tempmute:
    description: Tempmute a player
  unmute:
    description: Unmute a player
permissions:
    cookieApi.ban.team:
        description: Alle Permissions
        children:
            cookieApi.ban.ban: true
            cookieApi.ban.tempban: true
            cookieApi.ban.unban: true
            cookieApi.ban.kick: true
            cookieApi.ban.mute: true
            cookieApi.ban.tempmute: true
            cookieApi.ban.unmute: true
            cookieApi.ban.notifyinfo: true
        default: op
    cookieApi.ban.ban:
        description: Ban a player permanently
        default: op
    cookieApi.ban.tempban:
        description: Tempban a player
        default: op
    cookieApi.ban.unban:
        description: Unban a player
        default: op
    cookieApi.ban.kick:
        description: Kick a player
        default: op
    cookieApi.ban.mute:
        description: Mute a player permanently
        default: op
    cookieApi.ban.tempmute:
        description: Tempmute a player
        default: op
    cookieApi.ban.unmute:
        description: Unmute a player
        default: op