name: MineSuiteBan
version: ${project.version}
description: BanPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.ban.BanPlugin
load: POSTWORLD
depend: [MineSuiteCore]
api-version: 1.13
commands:
  ban:
    description: Ban a player
  tempban:
    description: Tempban a player
  kick:
    description: Kick a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  tempmute:
    description: Tempmute a player
  unmute:
    description: Unmute a player
permissions:
    mineSuite.ban.team:
        description: Alle Permissions
        children:
            mineSuite.ban.ban: true
            mineSuite.ban.tempban: true
            mineSuite.ban.unban: true
            mineSuite.ban.kick: true
            mineSuite.ban.mute: true
            mineSuite.ban.tempmute: true
            mineSuite.ban.unmute: true
            mineSuite.ban.notifyinfo: true
        default: op
    mineSuite.ban.ban:
        description: Ban a player permanently
        default: op
    mineSuite.ban.tempban:
        description: Tempban a player
        default: op
    mineSuite.ban.unban:
        description: Unban a player
        default: op
    mineSuite.ban.kick:
        description: Kick a player
        default: op
    mineSuite.ban.mute:
        description: Mute a player permanently
        default: op
    mineSuite.ban.tempmute:
        description: Tempmute a player
        default: op
    mineSuite.ban.unmute:
        description: Unmute a player
        default: op